language: go

go:
  - "1.10.x"

before_install:
  - curl https://glide.sh/get | sh

install:
  - glide install

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    rooms:
      - secure: "KlJiBYPK2jMzwFzKatHIMXgofdEhGZEzijloaW+bpFGXFiPBnZZc/drdnDNWYtfp2xPwBxdxEClmXqmIfO7JsvYJ5eQneMwjIjMEvVgssAYl+MtZt/hLxHp9D4mYdVwnEG3HkvaOHOgX2ph3sf9F49auh4gG4U8zlV9Rf7UaNMNIkEP85P55RxL8VNY4JaKwBAduRjgcqsi3fie1zg/+SNgB9wZqI5yptPDqHK1gfZj7Xn/7ataHV17gQ543HMawB2TbvT8JBh6g1nxk91HUd1+0N7exartq9rGgLkeh8hqq7mHZvjrTCOoYj4pnlHfxBZjpkgXzr/vsptNWxwIpbTdyxgMY17kd9YX7JhqdSiF+UquJqQJ2SelJXD3jyle17Oy3cGq/bVISOADaY+e27V2Hp/VsM5zK8c7tsRSZ3HpvSFbqTnHRT3/lXu0860VxnAsBqyfV/0NsW6bJs1h/aHPwAhIU5oNtmwo1JES17MzNZnfx0c0DOX5xl82/fXjoqTyVN3g3sZyicmA2bCPavw5oDcDyo38/0S0GpNnOF2QATm/ASjm4qjwD+1PTF7C900bteBhXTwkoTdZkroWMhb6qD9w1fjEwKmvRPXcTEuAqSsnuJkbp3RuIvXijBE51+rPNfBOI4RRkbXsvyd6jzQBJ++uZ2s+ADR0jYAK/cpQ="
